name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: [[[infra_repo]]]/.github/workflows/reusable-build.yml@[[[infra_ref]]]
    secrets: inherit
    with:
      project_name: "[[[project_name]]]"
      artifact_folder: "[[[artifact_folder]]]"
