name: pr-title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  conventional-title:
    uses: "[[[infra_repo]]]/.github/workflows/reusable-pr-title.yml@[[[infra_ref]]]"
    secrets: inherit
