name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    uses: "[[[infra_repo]]]/.github/workflows/reusable-release-please.yml@[[[infra_ref]]]"
    secrets: inherit
